world: world
startDelay: 60
intervalDelay: 120
saveThreads: 10
renderLoaded: false
zoomsIn: 1
zoomsOut: 3
discoverInterval: 2
markers:	# This default isn't necessary, but it's provided for reference.