name: RealtimeRender
main: net.nabaal.majiir.realtimerender.RealtimeRender
version: ${project.version}
author: Majiir
description: Maintains a frequently-updated map render.
commands:
  map:
    description: Prints a hello message
    usage: |
      /<command> - prints a hello message
